version: "3"

services:
  redis: 
    image: redis:6.2
    ports:
      - 6379:6379

  redis-ui:
    image: patrikx3/p3x-redis-ui:2021.4.162
    ports:
      - 7843:7843
    volumes:
      - /settings